# Generated by Django 4.2.6 on 2023-11-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_timestamp_alter_question_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.question'),
        ),
    ]
