# Generated by Django 4.2.6 on 2023-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_answer_like_count_remove_question_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
